import { createAsyncThunk, createSlice, createEntityAdapter } from '@reduxjs/toolkit';

const initialState = {};

export const gamesSlice = createSlice({
  name: 'games',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: builder => {
  },
});
  
export default gamesSlice.reducer;